CREATE TABLE IF NOT EXISTS users  (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL,
    email varchar(40) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS requests  (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL,
    description varchar(200) NOT NULL,
    author_id INTEGER references users(id) NOT NULL,
    created TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS items  (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL,
    description varchar(200) NOT NULL,
    owner_id INTEGER references users(id) NOT NULL,
    available BOOLEAN NOT NULL,
    request_id INTEGER references requests(id)
);


CREATE TABLE IF NOT EXISTS bookings  (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    item_id INTEGER references items(id) NOT NULL,
    booker_id INTEGER references users(id) NOT NULL,
    status varchar(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS comments  (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text varchar (200) NOT NULL,
    item_id INTEGER references items(id) NOT NULL,
    author_id INTEGER references users(id) NOT NULL,
    created TIMESTAMP NOT NULL
);